-- ============================================================
-- CONVO SUPABASE DATABASE
-- Current complete schema / clean-install reference.
-- Browser clients never access Supabase directly; the Cloudflare
-- Worker uses the service key.
-- ============================================================

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  pin text not null,
  name text not null,
  role text not null default 'user'
    check (role in ('user', 'admin', 'superadmin')),
  created_at timestamptz not null default now(),
  last_activity_at timestamptz
);

alter table public.users drop constraint if exists users_pin_key;
drop index if exists public.users_pin_role_key;

create unique index if not exists users_pin_normal_key
  on public.users(pin)
  where role <> 'superadmin';

create unique index if not exists users_pin_superadmin_key
  on public.users(pin)
  where role = 'superadmin';

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  is_private boolean not null default false
);

alter table public.channels
  add column if not exists is_private boolean not null default false;

create index if not exists idx_channels_private on public.channels(is_private);

create table if not exists public.channel_pages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  page_number integer not null check (page_number >= 1),
  starts_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (channel_id, page_number),
  unique (channel_id, id)
);

create table if not exists public.direct_conversations (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('dm', 'group_dm')),
  name text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade,
  page_id bigint,
  conversation_id bigint references public.direct_conversations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  parent_message_id bigint references public.messages(id) on delete cascade,
  quoted_message_id bigint references public.messages(id) on delete set null,
  text text not null,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz
);

alter table public.messages
  add column if not exists page_id bigint,
  add column if not exists conversation_id bigint,
  add column if not exists parent_message_id bigint,
  add column if not exists quoted_message_id bigint,
  add column if not exists edited_at timestamptz,
  add column if not exists deleted_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_target_check'
  ) then
    alter table public.messages
      add constraint messages_target_check
      check (
        (channel_id is not null and conversation_id is null) or
        (channel_id is null and conversation_id is not null)
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_page_fk'
  ) then
    alter table public.messages
      add constraint messages_page_fk
      foreign key (channel_id, page_id)
      references public.channel_pages(channel_id, id)
      on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_conversation_fk'
  ) then
    alter table public.messages
      add constraint messages_conversation_fk
      foreign key (conversation_id)
      references public.direct_conversations(id)
      on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_parent_fk'
  ) then
    alter table public.messages
      add constraint messages_parent_fk
      foreign key (parent_message_id)
      references public.messages(id)
      on delete cascade;
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'messages_quote_fk'
  ) then
    alter table public.messages
      add constraint messages_quote_fk
      foreign key (quoted_message_id)
      references public.messages(id)
      on delete set null;
  end if;
end
$$;

create table if not exists public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_viewed_at timestamptz,
  muted boolean not null default false,
  starred boolean not null default false,
  pinned boolean not null default false,
  notification_level text not null default 'all',
  primary key (channel_id, user_id)
);

create table if not exists public.channel_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete cascade,
  action text not null
    check (action in ('JOINED', 'VIEWED', 'POSTED', 'LEFT')),
  created_at timestamptz not null default now()
);

create table if not exists public.direct_members (
  conversation_id bigint not null references public.direct_conversations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  muted boolean not null default false,
  starred boolean not null default false,
  pinned boolean not null default false,
  notification_level text not null default 'all'
    check (notification_level in ('all','mentions','none')),
  primary key (conversation_id, user_id)
);

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create table if not exists public.message_stars (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.message_pins (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.message_mentions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  message_id bigint references public.messages(id) on delete cascade,
  conversation_id bigint references public.direct_conversations(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete cascade,
  type text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.message_attachments (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  bucket text not null default 'convo-files',
  object_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '5 hours'),
  deleted_at timestamptz
);

alter table public.message_attachments
  add column if not exists expires_at timestamptz,
  add column if not exists deleted_at timestamptz;

update public.message_attachments
set expires_at = created_at + interval '5 hours'
where expires_at is null;

alter table public.message_attachments
  alter column expires_at set default (now() + interval '5 hours');

alter table public.message_attachments
  alter column expires_at set not null;

create table if not exists public.chat_tasks (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade,
  conversation_id bigint references public.direct_conversations(id) on delete cascade,
  message_id bigint references public.messages(id) on delete set null,
  title text not null,
  description text,
  assignee_id bigint references public.users(id) on delete set null,
  created_by bigint not null references public.users(id) on delete cascade,
  due_at timestamptz,
  status text not null default 'open'
    check (status in ('open','completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint chat_tasks_target_check check (
    (channel_id is not null and conversation_id is null) or
    (channel_id is null and conversation_id is not null)
  )
);

-- ============================================================
-- INDEXES
-- ============================================================

create unique index if not exists idx_channel_pages_channel_page_number
  on public.channel_pages(channel_id, page_number);

create unique index if not exists channel_pages_channel_id_id_key
  on public.channel_pages(channel_id, id);

create index if not exists idx_channel_pages_channel_number
  on public.channel_pages(channel_id, page_number);

create index if not exists idx_messages_channel_created
  on public.messages(channel_id, created_at);

create index if not exists idx_messages_channel_page_created
  on public.messages(channel_id, page_id, created_at);

create index if not exists idx_messages_user
  on public.messages(user_id);

create index if not exists idx_messages_conversation_created
  on public.messages(conversation_id, created_at);

create index if not exists idx_messages_parent
  on public.messages(parent_message_id);

create index if not exists idx_activity_user_created
  on public.channel_activity(user_id, created_at);

create index if not exists idx_activity_channel_created
  on public.channel_activity(channel_id, created_at);

create index if not exists idx_activity_action
  on public.channel_activity(action);

create index if not exists idx_members_user
  on public.channel_members(user_id);

create index if not exists idx_reactions_message
  on public.message_reactions(message_id);

create index if not exists idx_stars_user
  on public.message_stars(user_id, created_at);

create index if not exists idx_pins_user
  on public.message_pins(user_id, created_at);

create index if not exists idx_mentions_user
  on public.message_mentions(user_id, created_at);

create index if not exists idx_notifications_user_created
  on public.notifications(user_id, created_at desc);

create index if not exists idx_notifications_unread
  on public.notifications(user_id, read_at);

create index if not exists idx_attachments_message
  on public.message_attachments(message_id);

create index if not exists idx_message_attachments_expiry
  on public.message_attachments(expires_at)
  where deleted_at is null;

create index if not exists idx_tasks_assignee_status
  on public.chat_tasks(assignee_id, status);

create index if not exists idx_direct_members_user
  on public.direct_members(user_id, conversation_id);

-- ============================================================
-- STORAGE
-- ============================================================

insert into storage.buckets (id, name, public, file_size_limit)
values ('convo-files', 'convo-files', false, 52428800)
on conflict (id) do update
set file_size_limit = excluded.file_size_limit;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.channel_pages enable row level security;
alter table public.messages enable row level security;
alter table public.channel_members enable row level security;
alter table public.channel_activity enable row level security;
alter table public.direct_conversations enable row level security;
alter table public.direct_members enable row level security;
alter table public.message_reactions enable row level security;
alter table public.message_stars enable row level security;
alter table public.message_pins enable row level security;
alter table public.message_mentions enable row level security;
alter table public.notifications enable row level security;
alter table public.message_attachments enable row level security;
alter table public.chat_tasks enable row level security;

-- No anon/authenticated policies are intentionally created.
-- All application access is routed through the Cloudflare Worker.
