-- ============================================================
-- CONVO SUPABASE DATABASE
-- ============================================================

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  pin text not null,
  name text not null,
  role text not null default 'user'
    check (role in ('user', 'admin', 'superadmin')),
  created_at timestamptz not null default now(),
  last_activity_at timestamptz
);

-- Normal users/admins and the Super Admin have separate PIN namespaces.
alter table public.users drop constraint if exists users_pin_key;
create unique index if not exists users_pin_role_key
  on public.users(pin, role);

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  name text unique not null,
  description text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_viewed_at timestamptz,
  primary key (channel_id, user_id)
);

create table if not exists public.channel_activity (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete cascade,
  action text not null
    check (action in ('JOINED', 'VIEWED', 'POSTED', 'LEFT')),
  created_at timestamptz not null default now()
);

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists idx_messages_channel_created
  on public.messages(channel_id, created_at);
create index if not exists idx_messages_user
  on public.messages(user_id);
create index if not exists idx_activity_user_created
  on public.channel_activity(user_id, created_at);
create index if not exists idx_activity_channel_created
  on public.channel_activity(channel_id, created_at);
create index if not exists idx_activity_action
  on public.channel_activity(action);
create index if not exists idx_members_user
  on public.channel_members(user_id);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.users enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;
alter table public.channel_members enable row level security;
alter table public.channel_activity enable row level security;

-- Browser does NOT access Supabase directly.
-- The Cloudflare Worker uses the Supabase secret key.
-- No anon/authenticated policies are intentionally created.
