-- Convo Google-Chat parity core
-- Adds DMs/group DMs, threads, reactions, mentions, stars, pins,
-- notifications, tasks, attachments and per-conversation preferences.

alter table public.messages
  alter column channel_id drop not null;

alter table public.messages
  add column if not exists conversation_id bigint,
  add column if not exists parent_message_id bigint,
  add column if not exists quoted_message_id bigint,
  add column if not exists edited_at timestamptz,
  add column if not exists deleted_at timestamptz;

create table if not exists public.direct_conversations (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('dm', 'group_dm')),
  name text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.direct_members (
  conversation_id bigint not null references public.direct_conversations(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  muted boolean not null default false,
  starred boolean not null default false,
  pinned boolean not null default false,
  notification_level text not null default 'all'
    check (notification_level in ('all','mentions','none')),
  primary key (conversation_id, user_id)
);

alter table public.messages
  add constraint messages_conversation_fk
  foreign key (conversation_id) references public.direct_conversations(id) on delete cascade;

alter table public.messages
  add constraint messages_parent_fk
  foreign key (parent_message_id) references public.messages(id) on delete cascade;

alter table public.messages
  add constraint messages_quote_fk
  foreign key (quoted_message_id) references public.messages(id) on delete set null;

alter table public.messages
  drop constraint if exists messages_target_check;

alter table public.messages
  add constraint messages_target_check
  check ((channel_id is not null and conversation_id is null) or
         (channel_id is null and conversation_id is not null));

create table if not exists public.message_reactions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create table if not exists public.message_stars (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.message_pins (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.message_mentions (
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  message_id bigint references public.messages(id) on delete cascade,
  conversation_id bigint references public.direct_conversations(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete cascade,
  type text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.message_attachments (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  bucket text not null default 'convo-files',
  object_path text not null,
  file_name text not null,
  mime_type text,
  file_size bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_tasks (
  id bigint generated by default as identity primary key,
  channel_id bigint references public.channels(id) on delete cascade,
  conversation_id bigint references public.direct_conversations(id) on delete cascade,
  message_id bigint references public.messages(id) on delete set null,
  title text not null,
  description text,
  assignee_id bigint references public.users(id) on delete set null,
  created_by bigint not null references public.users(id) on delete cascade,
  due_at timestamptz,
  status text not null default 'open' check (status in ('open','completed')),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint chat_tasks_target_check check (
    (channel_id is not null and conversation_id is null) or
    (channel_id is null and conversation_id is not null)
  )
);

alter table public.channel_members
  add column if not exists muted boolean not null default false,
  add column if not exists starred boolean not null default false,
  add column if not exists pinned boolean not null default false,
  add column if not exists notification_level text not null default 'all';

create index if not exists idx_messages_conversation_created
  on public.messages(conversation_id, created_at);
create index if not exists idx_messages_parent
  on public.messages(parent_message_id);
create index if not exists idx_reactions_message
  on public.message_reactions(message_id);
create index if not exists idx_stars_user
  on public.message_stars(user_id, created_at);
create index if not exists idx_pins_user
  on public.message_pins(user_id, created_at);
create index if not exists idx_mentions_user
  on public.message_mentions(user_id, created_at);
create index if not exists idx_notifications_user_created
  on public.notifications(user_id, created_at desc);
create index if not exists idx_notifications_unread
  on public.notifications(user_id, read_at);
create index if not exists idx_attachments_message
  on public.message_attachments(message_id);
create index if not exists idx_tasks_assignee_status
  on public.chat_tasks(assignee_id, status);
create index if not exists idx_direct_members_user
  on public.direct_members(user_id, conversation_id);

-- Private bucket. Files are served through the Worker after authorization.
insert into storage.buckets (id, name, public, file_size_limit)
values ('convo-files', 'convo-files', false, 52428800)
on conflict (id) do update set file_size_limit = excluded.file_size_limit;

alter table public.direct_conversations enable row level security;
alter table public.direct_members enable row level security;
alter table public.message_reactions enable row level security;
alter table public.message_stars enable row level security;
alter table public.message_pins enable row level security;
alter table public.message_mentions enable row level security;
alter table public.notifications enable row level security;
alter table public.message_attachments enable row level security;
alter table public.chat_tasks enable row level security;

-- Browser still never talks to Supabase directly; the Worker uses the secret key.
