-- Convo message-page foundation and integrity hardening

create table if not exists public.channel_pages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  page_number integer not null check (page_number >= 1),
  starts_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (channel_id, page_number)
);

alter table public.messages
  add column if not exists page_id bigint;

create unique index if not exists channel_pages_channel_id_id_key
  on public.channel_pages(channel_id, id);

create index if not exists idx_channel_pages_channel_number
  on public.channel_pages(channel_id, page_number);

create index if not exists idx_messages_channel_page_created
  on public.messages(channel_id, page_id, created_at);

-- Seed a first page for every existing channel, then repair any pre-existing
-- page numbering so the application can safely treat pages as contiguous.
insert into public.channel_pages (channel_id, page_number, starts_at)
select c.id, 1, coalesce(c.created_at, now())
from public.channels c
where not exists (
  select 1
  from public.channel_pages p
  where p.channel_id = c.id
);

with ranked as (
  select
    id,
    row_number() over (
      partition by channel_id
      order by page_number asc, created_at asc, id asc
    ) as repaired_page_number
  from public.channel_pages
)
update public.channel_pages p
set page_number = ranked.repaired_page_number
from ranked
where p.id = ranked.id
  and p.page_number <> ranked.repaired_page_number;

-- Existing channel messages without a page belong to page 1. DM messages keep
-- page_id NULL.
update public.messages m
set page_id = p.id
from public.channel_pages p
where m.channel_id = p.channel_id
  and p.page_number = 1
  and m.page_id is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'messages_page_fk'
  ) then
    alter table public.messages
      add constraint messages_page_fk
      foreign key (channel_id, page_id)
      references public.channel_pages(channel_id, id)
      on delete cascade;
  end if;
end
$$;

alter table public.channel_pages enable row level security;

notify pgrst, 'reload schema';
